// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniCourseCatalog.Mvc.Data;

#nullable disable

namespace MiniCourseCatalog.Mvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610133156_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<double>("TuitionFee")
                        .HasColumnType("REAL");

                    b.Property<int>("WarningThreshold")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 50,
                            CategoryId = 1,
                            CourseCode = "MTH00001",
                            CourseSku = "SKU-IT-CSLT",
                            Department = "Toán-Tin",
                            Instructor = "Nguyễn Hiền Lương",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cơ sở lập trình",
                            TuitionFee = 1500000.0,
                            WarningThreshold = 10
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 5,
                            CategoryId = 1,
                            CourseCode = "MTH00002",
                            CourseSku = "SKU-IT-CTDL",
                            Department = "Toán-Tin",
                            Instructor = "Hà Văn Thảo",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cấu trúc dữ liệu và giải thuật",
                            TuitionFee = 1800000.0,
                            WarningThreshold = 10
                        },
                        new
                        {
                            Id = 3,
                            AvailableSeats = 0,
                            CategoryId = 1,
                            CourseCode = "MTH00003",
                            CourseSku = "SKU-IT-OOP",
                            Department = "Toán-Tin",
                            Instructor = "Hà Văn Thảo",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lập trình hướng đối tượng",
                            TuitionFee = 2000000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 4,
                            AvailableSeats = 20,
                            CategoryId = 1,
                            CourseCode = "MTH00004",
                            CourseSku = "SKU-IT-WEB",
                            Department = "Toán-Tin",
                            Instructor = "Hà Văn Thảo",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lập trình web",
                            TuitionFee = 1600000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 5,
                            AvailableSeats = 15,
                            CategoryId = 2,
                            CourseCode = "ENG00001",
                            CourseSku = "SKU-LANG-IELTS",
                            Department = "Ngoại ngữ",
                            Instructor = "John Doe",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "IELTS 6.5 Cấp tốc",
                            TuitionFee = 4500000.0,
                            WarningThreshold = 5
                        });
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.CourseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CourseCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "IT",
                            Name = "Công nghệ thông tin"
                        },
                        new
                        {
                            Id = 2,
                            Code = "LANG",
                            Name = "Ngoại ngữ"
                        },
                        new
                        {
                            Id = 3,
                            Code = "SOFT",
                            Name = "Kỹ năng mềm"
                        });
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalTuition")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments", (string)null);
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.EnrollmentDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PriceApplied")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("EnrollmentId");

                    b.ToTable("EnrollmentDetails", (string)null);
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "hungtv@gmail.com",
                            FullName = "Trần Văn Hùng"
                        },
                        new
                        {
                            Id = 2,
                            Email = "maint@gmail.com",
                            FullName = "Nguyễn Thị Mai"
                        });
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Course", b =>
                {
                    b.HasOne("MiniCourseCatalog.Mvc.Models.CourseCategory", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Enrollment", b =>
                {
                    b.HasOne("MiniCourseCatalog.Mvc.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.EnrollmentDetail", b =>
                {
                    b.HasOne("MiniCourseCatalog.Mvc.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniCourseCatalog.Mvc.Models.Enrollment", "Enrollment")
                        .WithMany("EnrollmentDetails")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.CourseCategory", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Enrollment", b =>
                {
                    b.Navigation("EnrollmentDetails");
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
