// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniCourseCatalog.Mvc.Data;

#nullable disable

namespace MiniCourseCatalog.Mvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<double>("TuitionFee")
                        .HasColumnType("REAL");

                    b.Property<int>("WarningThreshold")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 20,
                            CategoryId = 1,
                            CourseCode = "ADD00031",
                            CourseSku = "SKU-25C2_1",
                            Department = "Anh văn",
                            Instructor = "Giảng viên Anh văn",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Anh văn 1 (Lớp 25C2_1)",
                            TuitionFee = 1500000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 9,
                            CategoryId = 1,
                            CourseCode = "ADD00031",
                            CourseSku = "SKU-25C3_1",
                            Department = "Anh văn",
                            Instructor = "Giảng viên Anh văn",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Anh văn 1 (Lớp 25C3_1)",
                            TuitionFee = 1500000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 3,
                            AvailableSeats = 8,
                            CategoryId = 1,
                            CourseCode = "ADD00031",
                            CourseSku = "SKU-25C4_1",
                            Department = "Anh văn",
                            Instructor = "Giảng viên Anh văn",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Anh văn 1 (Lớp 25C4_1)",
                            TuitionFee = 1500000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 4,
                            AvailableSeats = 6,
                            CategoryId = 1,
                            CourseCode = "ADD00031",
                            CourseSku = "SKU-25S4_1",
                            Department = "Anh văn",
                            Instructor = "Giảng viên Anh văn",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Anh văn 1 (Lớp 25S4_1)",
                            TuitionFee = 1500000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 5,
                            AvailableSeats = 16,
                            CategoryId = 1,
                            CourseCode = "ADD00032",
                            CourseSku = "SKU-AV2-25S4_1",
                            Department = "Anh văn",
                            Instructor = "Giảng viên Anh văn",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Anh văn 2 (Lớp 25S4_1)",
                            TuitionFee = 1500000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 6,
                            AvailableSeats = 2,
                            CategoryId = 1,
                            CourseCode = "ADD00032",
                            CourseSku = "SKU-AV2-25S5_1",
                            Department = "Anh văn",
                            Instructor = "Giảng viên Anh văn",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Anh văn 2 (Lớp 25S5_1)",
                            TuitionFee = 1500000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 7,
                            AvailableSeats = 23,
                            CategoryId = 1,
                            CourseCode = "ADD00032",
                            CourseSku = "SKU-AV2-25S6_1",
                            Department = "Anh văn",
                            Instructor = "Giảng viên Anh văn",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Anh văn 2 (Lớp 25S6_1)",
                            TuitionFee = 1500000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 8,
                            AvailableSeats = 10,
                            CategoryId = 1,
                            CourseCode = "ADD00033",
                            CourseSku = "SKU-AV3-25C2_1",
                            Department = "Anh văn",
                            Instructor = "Giảng viên Anh văn",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Anh văn 3 (Lớp 25C2_1)",
                            TuitionFee = 1500000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 9,
                            AvailableSeats = 0,
                            CategoryId = 2,
                            CourseCode = "BAA00003",
                            CourseSku = "SKU-HCM-24_7",
                            Department = "Lý luận chính trị",
                            Instructor = "Giảng viên LLCT",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tư tưởng Hồ Chí Minh (Lớp 24_7)",
                            TuitionFee = 1000000.0,
                            WarningThreshold = 10
                        },
                        new
                        {
                            Id = 10,
                            AvailableSeats = 0,
                            CategoryId = 2,
                            CourseCode = "BAA00003",
                            CourseSku = "SKU-HCM-24_5",
                            Department = "Lý luận chính trị",
                            Instructor = "Giảng viên LLCT",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tư tưởng Hồ Chí Minh (Lớp 24_5)",
                            TuitionFee = 1000000.0,
                            WarningThreshold = 10
                        },
                        new
                        {
                            Id = 11,
                            AvailableSeats = 0,
                            CategoryId = 2,
                            CourseCode = "BAA00004",
                            CourseSku = "SKU-PLDC-25CTT6",
                            Department = "Lý luận chính trị",
                            Instructor = "Giảng viên LLCT",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pháp luật đại cương (Lớp 25CTT6)",
                            TuitionFee = 1500000.0,
                            WarningThreshold = 10
                        },
                        new
                        {
                            Id = 12,
                            AvailableSeats = 0,
                            CategoryId = 2,
                            CourseCode = "BAA00004",
                            CourseSku = "SKU-PLDC-25CTT4",
                            Department = "Lý luận chính trị",
                            Instructor = "Giảng viên LLCT",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pháp luật đại cương (Lớp 25CTT4)",
                            TuitionFee = 1500000.0,
                            WarningThreshold = 10
                        },
                        new
                        {
                            Id = 13,
                            AvailableSeats = 0,
                            CategoryId = 2,
                            CourseCode = "BAA00101",
                            CourseSku = "SKU-MLN-25KVL2",
                            Department = "Lý luận chính trị",
                            Instructor = "Giảng viên LLCT",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Triết học Mác - Lênin (Lớp 25KVL2)",
                            TuitionFee = 1500000.0,
                            WarningThreshold = 10
                        },
                        new
                        {
                            Id = 14,
                            AvailableSeats = 0,
                            CategoryId = 2,
                            CourseCode = "BAA00104",
                            CourseSku = "SKU-LSD-25DTV2",
                            Department = "Lý luận chính trị",
                            Instructor = "Giảng viên LLCT",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lịch sử Đảng Cộng sản Việt Nam (Lớp 25DTV2)",
                            TuitionFee = 1000000.0,
                            WarningThreshold = 10
                        },
                        new
                        {
                            Id = 15,
                            AvailableSeats = 0,
                            CategoryId = 3,
                            CourseCode = "BAA00005",
                            CourseSku = "SKU-KTDC-25KDC1",
                            Department = "Kinh tế",
                            Instructor = "Giảng viên Kinh tế",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kinh tế đại cương (Lớp 25KDC1)",
                            TuitionFee = 1000000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 16,
                            AvailableSeats = 0,
                            CategoryId = 3,
                            CourseCode = "BAA00006",
                            CourseSku = "SKU-TLDC-25_1",
                            Department = "Tâm lý",
                            Instructor = "Giảng viên Tâm lý",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tâm lý đại cương (Lớp 25_1)",
                            TuitionFee = 1000000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 17,
                            AvailableSeats = 0,
                            CategoryId = 3,
                            CourseCode = "BAA00008",
                            CourseSku = "SKU-KN-25KDL",
                            Department = "Kỹ năng",
                            Instructor = "Giảng viên Kỹ năng",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kỹ năng làm việc nhóm và học tập",
                            TuitionFee = 1000000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 18,
                            AvailableSeats = 0,
                            CategoryId = 4,
                            CourseCode = "BAA00021",
                            CourseSku = "SKU-TD1-25TNT2",
                            Department = "Thể chất",
                            Instructor = "Giảng viên Thể dục",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Thể dục 1 (Lớp 25TNT2)",
                            TuitionFee = 1000000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 19,
                            AvailableSeats = 3,
                            CategoryId = 4,
                            CourseCode = "BAA00022",
                            CourseSku = "SKU-TD2-25VT_T2Ti1",
                            Department = "Thể chất",
                            Instructor = "Giảng viên Thể dục",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Thể dục 2 (Lớp 25VT_T2Ti1)",
                            TuitionFee = 1000000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 20,
                            AvailableSeats = 0,
                            CategoryId = 4,
                            CourseCode = "BAA00022",
                            CourseSku = "SKU-TD2-25VT_T3Ti1",
                            Department = "Thể chất",
                            Instructor = "Giảng viên Thể dục",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Thể dục 2 (Lớp 25VT_T3Ti1)",
                            TuitionFee = 1000000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 21,
                            AvailableSeats = 0,
                            CategoryId = 5,
                            CourseCode = "BIO00001",
                            CourseSku = "SKU-SDC1-25HDH1",
                            Department = "Sinh học",
                            Instructor = "Giảng viên Sinh học",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sinh đại cương 1 (Lớp 25HDH1)",
                            TuitionFee = 1500000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 22,
                            AvailableSeats = 0,
                            CategoryId = 5,
                            CourseCode = "BIO00002",
                            CourseSku = "SKU-SDC2-25CSH3",
                            Department = "Sinh học",
                            Instructor = "Giảng viên Sinh học",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sinh đại cương 2 (Lớp 25CSH3)",
                            TuitionFee = 1500000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 23,
                            AvailableSeats = 0,
                            CategoryId = 5,
                            CourseCode = "CHE00001",
                            CourseSku = "SKU-HDC1-25CVD1",
                            Department = "Hóa học",
                            Instructor = "Giảng viên Hóa học",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hóa đại cương 1 (Lớp 25CVD1)",
                            TuitionFee = 1500000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 24,
                            AvailableSeats = 0,
                            CategoryId = 6,
                            CourseCode = "CSC00003",
                            CourseSku = "SKU-THCS-C2A",
                            Department = "Toán-Tin",
                            Instructor = "Giảng viên Tin học",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tin học cơ sở (Lớp C2A)",
                            TuitionFee = 1500000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 25,
                            AvailableSeats = 0,
                            CategoryId = 6,
                            CourseCode = "MTH00013",
                            CourseSku = "SKU-VTP2A-25KDL1",
                            Department = "Toán-Tin",
                            Instructor = "Giảng viên Toán",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Vi tích phân 2A (Lớp 25KDL1)",
                            TuitionFee = 1500000.0,
                            WarningThreshold = 5
                        },
                        new
                        {
                            Id = 26,
                            AvailableSeats = 0,
                            CategoryId = 6,
                            CourseCode = "MTH00055",
                            CourseSku = "SKU-CSLT-25TTH1",
                            Department = "Toán-Tin",
                            Instructor = "Giảng viên Tin học",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cơ sở lập trình (Lớp 25TTH1)",
                            TuitionFee = 2000000.0,
                            WarningThreshold = 10
                        },
                        new
                        {
                            Id = 27,
                            AvailableSeats = 0,
                            CategoryId = 7,
                            CourseCode = "PHY00001",
                            CourseSku = "SKU-VLDC1-25CTT5",
                            Department = "Vật lý",
                            Instructor = "Giảng viên Vật lý",
                            LastUpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Vật lý đại cương 1 (Lớp 25CTT5)",
                            TuitionFee = 1500000.0,
                            WarningThreshold = 5
                        });
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.CourseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CourseCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AV",
                            Name = "Anh văn"
                        },
                        new
                        {
                            Id = 2,
                            Code = "LLCT",
                            Name = "Lý luận chính trị"
                        },
                        new
                        {
                            Id = 3,
                            Code = "KHTN",
                            Name = "Khoa học tự nhiên & Đại cương"
                        },
                        new
                        {
                            Id = 4,
                            Code = "TD",
                            Name = "Thể dục"
                        },
                        new
                        {
                            Id = 5,
                            Code = "SHHH",
                            Name = "Sinh học & Hóa học"
                        },
                        new
                        {
                            Id = 6,
                            Code = "THTH",
                            Name = "Toán học & Tin học"
                        },
                        new
                        {
                            Id = 7,
                            Code = "VL",
                            Name = "Vật lý"
                        });
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalTuition")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments", (string)null);
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.EnrollmentDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PriceApplied")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("EnrollmentId");

                    b.ToTable("EnrollmentDetails", (string)null);
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "hungtv@gmail.com",
                            FullName = "Trần Văn Hùng"
                        },
                        new
                        {
                            Id = 2,
                            Email = "maint@gmail.com",
                            FullName = "Nguyễn Thị Mai"
                        });
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Course", b =>
                {
                    b.HasOne("MiniCourseCatalog.Mvc.Models.CourseCategory", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Enrollment", b =>
                {
                    b.HasOne("MiniCourseCatalog.Mvc.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.EnrollmentDetail", b =>
                {
                    b.HasOne("MiniCourseCatalog.Mvc.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniCourseCatalog.Mvc.Models.Enrollment", "Enrollment")
                        .WithMany("EnrollmentDetails")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.CourseCategory", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Enrollment", b =>
                {
                    b.Navigation("EnrollmentDetails");
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
